@startuml walewatcher
hide empty members

class Portfolio {
    Names(): []string
    Project(name: string): *ComposerProject
}

Portfolio -> "  1+" ComposerProject : "projects"

class ComposerProject {
    Name: string
    Containers(): []*Container
    ContainerNames(): []string
    Container(id: string): *Container
}

ComposerProject -> "    *" Container : "Containers"

class Container {
    ID: string
    Name: string
    Labels: map[string]string
    PID: int
    ProjectName(): string
}

Container -> ComposerProject : "ProjectName"

@enduml
