name: build and test
on:
  push:
    branches:
    - master

jobs:

  buildandtest:
    name: Build and Test on Go ${{matrix.go}}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: ['1.17', '1.16']
    steps:
    - name: Set up Go ${{matrix.go}}
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.go}}
      id: go

    - name: Set up Go for root
      run: |
        sudo ln -sf `which go` `sudo which go` || true
        sudo go version
        
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test Go packages
      run: go test -v -exec sudo ./... && go test -v ./...
